# Generated by Django 2.2.9 on 2019-12-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
    ]
